package Servidor;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pelon
 */
public class others extends javax.swing.JFrame {

    /**
     * Creates new form others
     */
    public final Font defecto = new Font("San Francisco Display", Font.BOLD, 13);
    public final Color defectoColor = Color.WHITE;
    public final JPanel colorLabel1= new JPanel();
    view v = new view();
    
    
    public others() {
        initComponents();
        setTitle("Otros dispositivos- Servidor");
        agregarIcono();
        this.getContentPane().setBackground(SeasunColor.GRIS);
        this.setLocationRelativeTo(null);
        jLabel10.setFont(defecto);
        jLabel10.setForeground(defectoColor);
        jLabel1.setFont(defecto);
        jLabel1.setForeground(defectoColor);
        jLabel1.setBackground(SeasunColor.AZUL);
        jLabel2.setFont(defecto);
        jLabel2.setForeground(defectoColor);
        jLabel3.setFont(defecto);
        jLabel3.setForeground(defectoColor);
        jLabel4.setFont(defecto);
        jLabel4.setForeground(defectoColor);
        jLabel5.setFont(defecto);
        jLabel5.setForeground(defectoColor);
        jLabel6.setFont(defecto);
        jLabel6.setForeground(defectoColor);
        jLabel7.setFont(defecto);
        jLabel7.setForeground(defectoColor);
        jLabel8.setFont(defecto);
        jLabel8.setForeground(defectoColor);
        jLabel9.setFont(defecto);
        jLabel9.setForeground(defectoColor);
        send.setBackground(SeasunColor.VERDE);
        send.setForeground(defectoColor);
        send.setFont(defecto);
        close.setBackground(SeasunColor.VERDE);
        close.setForeground(defectoColor);
        close.setFont(defecto);
        edificio.setBackground(SeasunColor.AZUL);
        edificio.setForeground(defectoColor);
        edificio.setFont(defecto);
        nivel.setBackground(SeasunColor.AZUL);
        nivel.setForeground(defectoColor);
        nivel.setFont(defecto);
        area.setBackground(SeasunColor.AZUL);
        area.setForeground(defectoColor);
        area.setFont(defecto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        product = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        serial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        responsable = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        send = new javax.swing.JButton();
        close = new javax.swing.JButton();
        edificio = new javax.swing.JComboBox<>();
        nivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        area = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Otro dispositivos");

        jLabel2.setText("Producto");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("# Serie");

        jLabel6.setText("Edificio");

        jLabel7.setText("Responsable");

        send.setText("Enviar");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        close.setText("Cerrar");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        edificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        edificio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                edificioItemStateChanged(evt);
            }
        });

        nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        nivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nivelItemStateChanged(evt);
            }
        });

        jLabel8.setText("Nivel");

        jLabel9.setText("Área");

        area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel10.setText("Observaciones");

        observaciones.setColumns(20);
        observaciones.setLineWrap(true);
        observaciones.setRows(5);
        observaciones.setAutoscrolls(false);
        jScrollPane2.setViewportView(observaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(product, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(serial, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(model, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brand, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(edificio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(send)
                                    .addComponent(jLabel7)
                                    .addComponent(responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(area, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(close))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(responsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(send)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        
        try{
            if(product.getText().equals("") || brand.getText().equals("") || model.getText().equals("") || serial.getText().equals("") || responsable.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Faltan datos");
        }else{
            
            Connection con = v.getConnection();
            
            PreparedStatement pst2 = con.prepareStatement("SELECT * FROM dispositivos where serialNumber=?");
            pst2.setString(1, serial.getText());
            ResultSet rs = pst2.executeQuery();

            if(rs.next()){
                PreparedStatement psDel = con.prepareStatement("DELETE FROM dispositivos where serialNumber=?");
                psDel.setString(1, serial.getText());
                psDel.executeUpdate();
                psDel.close();
            }
            pst2.close();
            
            
            String command = "Insert into dispositivos (producto, marca, modelo, serialNumber, area, responsable,edificio, nivel, observaciones) Values (?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(command);
            //preparedStatements
            pst.setString(1, product.getText());
            pst.setString(2, brand.getText());
            pst.setString(3, model.getText());
            pst.setString(4, serial.getText());
            pst.setString(5, area.getSelectedItem().toString());
            pst.setString(6, responsable.getText());
            pst.setString(7, edificio.getSelectedItem().toString());
            pst.setString(8, nivel.getSelectedItem().toString());
            pst.setString(9, observaciones.getText());
            pst.executeUpdate();
            pst.close();
            
            PreparedStatement pst1 = con.prepareStatement("SELECT * FROM dispositivos where serialNumber=?");
            pst1.setString(1, serial.getText());
            ResultSet rs1 = pst1.executeQuery();

            if(rs1.next()){
                JOptionPane.showMessageDialog(null,"Registro Agregado");
            }else{
                JOptionPane.showMessageDialog(null, "Ocurrio un error");
            }
            pst1.close();
            con.close();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_sendActionPerformed

    private void edificioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_edificioItemStateChanged
      Statement st;
                ResultSet rs;
                 try {
                     nivel.removeAllItems();
            Connection con = v.getConnection();
            st = con.createStatement();
            String command = "select DISTINCT nivel from edificios where edificio = '"+ edificio.getSelectedItem().toString()+"'";
            rs = st.executeQuery(command);
            
            while(rs.next()){
                nivel.addItem(rs.getString(1));
            }
            
            con.close();
                 }
                 catch(NullPointerException ex){            
            
        }       catch (SQLException ex) {
            Logger.getLogger(others.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edificioItemStateChanged

    private void nivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nivelItemStateChanged

                Statement st;
                ResultSet rs;
                 try {
                     area.removeAllItems();
            Connection con = v.getConnection();
            st = con.createStatement();
            String command = "select area from edificios where nivel = '"+ nivel.getSelectedItem().toString()+"'";
            rs = st.executeQuery(command);
            
            while(rs.next()){
                area.addItem(rs.getString(1));
            }
            
            con.close();
                 }
                 catch(NullPointerException ex){            
            
        }       catch (SQLException ex) {
            Logger.getLogger(others.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nivelItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Statement st;
        ResultSet rs;
        try {
            edificio.removeAllItems();     
            Connection con = v.getConnection();
            st = con.createStatement();
            String command = "select DISTINCT edificio from edificios";
            rs = st.executeQuery(command);
            
            while(rs.next()){
                edificio.addItem(rs.getString(1));
            }
            
            con.close();
                 }
                 catch(NullPointerException ex){            
            
        }       catch (SQLException ex) {
            Logger.getLogger(others.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new others().setVisible(true);
            }
        });
    }
    public void agregarIcono(){
        try{ 
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("favicon.png")));
        } catch (Exception e){
            e.getMessage();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> area;
    private javax.swing.JTextField brand;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> edificio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField model;
    private javax.swing.JComboBox<String> nivel;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JTextField product;
    private javax.swing.JTextField responsable;
    private javax.swing.JButton send;
    private javax.swing.JTextField serial;
    // End of variables declaration//GEN-END:variables
}
